name: linux

on:
  push:
    branches: [ master, my-rollback-branch ]
  pull_request:
    branches: [ master, my-rollback-branch ]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - name: Install dependencies
      run: pacman -Syu --noconfirm && pacman -S --noconfirm --needed libxinerama freetype2 debuginfod wayland dbus libxkbcommon libglvnd meson cmake git wayland-protocols libxrandr nodejs
    - name: Trust git repo
      run: git config --global --add safe.directory '*'
    - uses: actions/checkout@v4
    - name: Profiler GUI
      run: |
        cmake -B profiler/build -S profiler -DCMAKE_BUILD_TYPE=Release -DGIT_REV=${{ github.sha }} -DLEGACY=1
        cmake --build profiler/build --parallel
    - uses: actions/upload-artifact@v4
      with:
        name: tracy-profiler
        path: profiler/build/tracy-profiler
