name: linux

on:
  push:
    branches: [ master, my-rollback-branch ]
  pull_request:
    branches: [ master, my-rollback-branch ]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - name: Install dependencies
      run: pacman -Syu --noconfirm && pacman -S --noconfirm --needed glfw libxinerama freetype2 debuginfod wayland dbus libxkbcommon libglvnd meson cmake git wayland-protocols libxrandr nodejs
    - name: Trust git repo
      run: git config --global --add safe.directory '*'
    - uses: actions/checkout@v4
    - name: Profiler GUI
      run: |
        cmake -B profiler/build -S profiler -DCMAKE_BUILD_TYPE=Release -DGIT_REV=${{ github.sha }} -DLEGACY=1 -DCMAKE_CXX_FLAGS="-Wno-stringop-overflow -Wno-error"
        cmake --build profiler/build --parallel
    - name: Archive profiler binary
      run: |
        tar -czvf tracy-profiler.tar.gz -C profiler/build tracy-profiler
    - uses: actions/upload-artifact@v4
      with:
        name: tracy-profiler
        path: tracy-profiler.tar.gz
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: release-${{ github.run_id }}
        name: Release ${{ github.run_id }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: release-${{ github.run_id }}
        name: tracy-profiler
        files: tracy-profiler.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

